/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; } | { pathname: `/delivery/active`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/add-stops`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/history`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/profile-setup`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownOutputParams; } | { pathname: `/delivery/active`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/add-stops`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/history`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownOutputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/profile-setup${`?${string}` | `#${string}` | ''}` | `/auth/verify${`?${string}` | `#${string}` | ''}` | `/delivery/active${`?${string}` | `#${string}` | ''}` | `/tabs/add-stops${`?${string}` | `#${string}` | ''}` | `/tabs/history${`?${string}` | `#${string}` | ''}` | `/tabs/home${`?${string}` | `#${string}` | ''}` | `/tabs/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/profile-setup`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify`; params?: Router.UnknownInputParams; } | { pathname: `/delivery/active`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/add-stops`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/history`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/home`; params?: Router.UnknownInputParams; } | { pathname: `/tabs/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
